version: '3'
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
